backend:
  name: github
  repo: mtws/mtws.github.io
  branch: master
  site_domain: pensive-curran-f7b93d.netlify.com
media_folder: public/assets
public_folder: /assets
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/posts
    label: "Posts" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime" }
      - {label: "Cover Image", name: "coverImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Author"
        name: "author"
        widget: object
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Picture, name: picture, widget: image}
      - label: "og:image"
        name: "ogImage"
        widget: object
        fields:
          - {label: Url, name: url, widget: image}